version: 2

sources:
  - name: silver
    catalog: tpch_dev
    schema: silver
    tables:
      - name: orders
      - name: lineitem
      - name: customer
      - name: nation
      - name: region
      - name: supplier